### PR TITLE
fix: #1350 valueTransformer transform values to null

### LINKED ISSUE #1350: FormBuilderTextField sets field state to '' even though transformer sets return to null
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
FormBuilderTextField(
                  name: 'writeSize',
                  decoration: const InputDecoration(
                    labelText: 'Write Size (bytes)',
                  ),
                  initialValue: writeSize.toString(),
                  validator: FormBuilderValidators.compose(
                    [
                      FormBuilderValidators.integer(),
                      FormBuilderValidators.min(1),
                      FormBuilderValidators.max(128),
                    ],
                  ),
                  valueTransformer: (value) => int.tryParse(value!),
                ),
```

</details>

### Current Behavior

Trying to use FormBuilderTextField to create a field that accepts either an integer or nothing.  The int.tryParse call inside valueTransformer returns null if value is an empty string, however the field state gets set to an empty string rather than null.  This forces me to transform the transform so that I can get to the needed null.

While experimenting I took the int.tryParse out of the equation by transforming to null no matter what, e.g. valueTransformer: (value) => null.  The field state is still changed to ''.

### Expected Behavior

If I am intentionally transforming the value to null, I expect the field state to be null and not an empty string.  Am I missing a necessary property?

### Steps To Reproduce

Incorporate the above field widget sample into a form and try it out.

### Aditional information

I know I can work around this by transforming all of the empty integer fields to null on submit, but this should be unnecessary.  Please let me know if this can be fixed or if I'm missing something.

### PR DESCRIPTION
**Pull request by BrottarBasse**
Fix for issue 1350 with some changes to tests. This fix makes it so that valueTransformer can transform values to null.

## Connection with issue(s)

Close #1350 

Connected to #???

## Solution description

Changes to implementation of value transformer so that it is still used if value is transformed to null.
I also found that the tests also had flipped values in the expect functions (actual and matcher was wrong way around)

## To Do

- [ x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [ x] Check the original issue to confirm it is fully satisfied
- [ x] Add solution description to help guide reviewers
- [ x] Add unit test to verify new or fixed behaviour
- [ x] If apply, add documentation to code properties and package readme

### CODE REVIEW

File: lib/src/form_builder_field.dart [hunk 1]
```diff
@@ -88,7 +88,7 @@ class FormBuilderFieldState<F extends FormBuilderField<T>, T>
       (_formBuilderState?.initialValue ??
           const <String, dynamic>{})[widget.name] as T?;
 
-  dynamic get transformedValue => widget.valueTransformer?.call(value) ?? value;
+  dynamic get transformedValue => widget.valueTransformer == null ? value : widget.valueTransformer!(value);
```
Comment (deandreamatias) [inline lib/src/form_builder_field.dart:91]: Why change this? Isn't the same thing that have before

Comment (BrottarBasse) [reply lib/src/form_builder_field.dart:91]: The main problem this is causing is using valueTransformer in textfield for example an "age" field that is optional.
If someone starts typing an age and then erases it the value is an empty String. Here the value transformer above should return null but instead you get the empty String as a return. The transformer is being run but because it returned null its value is discarded and instead you get "" as a return.

**Comment by deandreamatias** [comment]
HI @BrottarBasse please resolve pipeline errors (format `form_builder.dart`) to could be merge

**Comment by BrottarBasse** [comment]
> HI @BrottarBasse please resolve pipeline errors (format `form_builder.dart`) to could be merge

Since my fix contains changes to form_builder_field.dart the checks fail.
