### PR TITLE
fix: add deep compare to update dropdown items

### LINKED ISSUE #1252: [FormBuilderDropdown]: <If onChanged Function is added, the FormBuilderDropdown stop working>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.0

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale es-MX)
    • Flutter version 3.10.0 on channel stable at C:\Users\Carlos\flutter_sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Carlos\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Carlos\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

• No issues found!

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter FormBuilder Demo',
      debugShowCheckedModeBanner: false,
      localizationsDelegates: [
        FormBuilderLocalizations.delegate,
        ...GlobalMaterialLocalizations.delegates,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: FormBuilderLocalizations.supportedLocales,
      home: Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  int? selectedLineId;
  final GlobalKey<FormBuilderState> _formKey = GlobalKey<FormBuilderState>();
  late List<Line> lines;

  @override
  void initState() {
    lines = _initLines();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Example')),
      body: FormBuilder(
        key: _formKey,
        child: Column(
          children: <Widget>[
            FormBuilderDropdown<int>(
              name: 'lineId',
              valueTransformer: (int? val) => val?.toInt(),
              decoration: const InputDecoration(
                  labelText: 'lines', icon: Icon(Icons.ad_units)),
              validator: FormBuilderValidators.compose(
                  [FormBuilderValidators.required()]),
              items: lines
                  .map((Line item) => DropdownMenuItem<int>(
                        value: item.id,
                        child: Text(item.name),
                      ))
                  .toList(),
              onChanged: (int? value) {
                setState(() {
                  selectedLineId = value;
                });
              },
            )
          ],
        ),
      ),
    );
  }

  List<Line> _initLines() {
    //This is just for test purpose
    return <Line>[
      Line(
        id: 1,
        name: 'Test',
      ),
      Line(
        id: 2,
        name: 'Test 2',
      )
    ];
  }
}

class Line {
  final int id;
  final String name;

  Line({required this.id, required this.name});
}

```

</details>

### Current Behavior

If I add setState inside of onChanged the FormBuilderDropdown is not working correctly:

If I select an option:

 

Then nothing is selected: 

On previous version it was working once I update to 9.0.0 it stop to works. 

### Expected Behavior

If I select an option 

For example: 

Then the option is selected:

### Steps To Reproduce

1. Add setState to onChanged

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by deandreamatias**
## Connection with issue(s)

Close #1252 

Connected to #687 
Connected to #1239 

## Solution description

Add a deep compare to reset dropdown only when items are really different.

I considered remove the verification and transfer it responsibility to reset dropdown to developer users (like @danvick says on [this comment](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1252#issuecomment-1617920942)), but I thinks that this behavior is a important to have embedded on package because is a feature that able implement related fields with minor effort.

## Screenshots or Videos

Test behavior of original issue (#1252)

[Screencast from 15-07-23 14:23:59.webm](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/21011641/3ab9300c-27d7-44e0-afe0-6bc121cfd651)

Test behavior of related issue (#687)

[Screencast from 15-07-23 14:25:01.webm](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/21011641/ce421610-1bd1-4015-b2b9-50ff393b9eb7)

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

File: lib/src/fields/form_builder_dropdown.dart [hunk 1]
```diff
@@ -299,8 +300,28 @@ class _FormBuilderDropdownState<T>
...
+    if ((!listEquals(oldChilds, currentlyChilds) ||
+            !listEquals(oldValues, currentlyValues)) &&
+        (widget.items.contains(initialValue) ||
+            _emptyValidator<T>(initialValue))) {
       setValue(initialValue);
     }
   }
 }
+
+bool _emptyValidator<T>(T? value) {
```
Comment (danvick) [inline lib/src/fields/form_builder_dropdown.dart:319]: Could you put this function in a place where it can be reused? 

I feel it's pretty generic and could be used anywhere else if needed.

Maybe create a file named `lib/src/utils/utils.dart` and have it there? This is optional though.

**Review by danvick — CHANGES_REQUESTED** [review]
Hi @deandreamatias, please check the suggested changes.

**Comment by danvick** [comment]
Other than the highlighted error, I think the code is well done.

HOWEVER, there is still a loophole to this condition `currentlyValues.contains(initialValue)`.
As I had indicated in point number 2 of [my original comment](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1252), if the `List` contains objects of a class that doesn't override the equality operator (==), the condition will still return `false`.

Example:
```Dart
main(){
  print([
    Continent(id: 1, name: 'Africa'), 
    Continent(id: 2, name: 'Asia'), 
    Continent(id: 3, name: 'Europe'),
  ].contains(Continent(id: 1, name: 'Africa'))); // PRINTS `true` because the Continent class is 'equatable'

  // WHILE

  print([
    Country(id: 2, name: 'India', continentId: 2),
    Country(id: 3, name: 'Spain', continentId: 3),
    Country(id: 3, name: 'France', continentId: 3),
  ].contains(Country(id: 2, name: 'India', continentId: 2))); // PRINTS `false` because the Country class is NOT 'equatable'

}
class Continent {
  final int id;
  final String name;

  Continent({required this.id, required this.name});

  @override
  operator ==(Object other){
    return other is Continent && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

class Country {
  final int id;
  final String name;
  final int continentId;

  Country({required this.id, required this.name, required this.continentId});
}
```

It is therefore up to the user to make sure that that's the case.

For example, in the [example of the original issue that we're solving](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1252), if the `Line` class was "equitable", the issue wouldn't have occurred in the first place.

Since there's nothing more we could do about that, I applaud @deandreamatias's efforts to prevent the user of the library from shooting themselves in the foot. Good work!

You can resolve the reviews then go ahead and merge. Thanks.
